- project:
    default-branch: main
    gh_check:
      jobs:
        - bazel-build
    gh_gate:
      jobs:
        - bazel-build
    gh_post:
      jobs:
        - bazel-build
    gh_tag:
      jobs:
        - bazel-build

- job:
    name: bazel-build
    description: "Run Bazel build"
    run: playbooks/run-bazel.yaml
    nodeset:
      nodes:
        - name: ubuntu-jammy
          label: ubuntu-jammy # Adjust based on the node type
